export const AUTH_INITIAL_STATE = 'AUTH_INITIAL_STATE';
export const AUTH_LOGIN_USER = 'AUTH_LOGIN_USER';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';

export const RECORD_INITIAL_STATE = 'RECORD_INITIAL_STATE';
export const RECORD_CHANGE_LIST_STATE = 'RECORD_CHANGE_LIST_STATE';
export const RECORD_CHANGE_CURRENT_STATE = 'RECORD_CHANGE_CURRENT_STATE';

export const SETTINGS_INITIAL_STATE = 'SETTINGS_INITIAL_STATE';
export const SETTINGS_CHANGE_LANG = 'SETTINGS_CHANGE_LANG';
export const SETTINGS_LOAD_COUNTRIES = 'SETTINGS_LOAD_COUNTRIES';
export const SETTINGS_CHAGE_DATA_VIEW = 'SETTINGS_CHAGE_DATA_VIEW';

export const USER_INITIAL_STATE = 'USER_INITIAL_STATE';
export const USER_INSERT = 'USER_INSERT';
export const USER_DELETE = 'USER_DELETE';
export const USER_CHANGE = 'USER_CHANGE';

export const MESSAGE_INITIAL_STATE = 'MESSAGE_INITIAL_STATE';
export const MESSAGE_CHANGE_STATE = 'MESSAGE_CHANGE_STATE';
